### ISSUE TITLE
v1 milestone

### ISSUE THREAD

**Issue by chriscalo** [chriscalo/express-fs-autorouter#1]
- [ ] make it configurable: #2 
- [ ] file name patterns for HTTP method: #3
- [ ] support Nuxt3-like placeholders: #4
- [ ] use [chokidar](https://github.com/paulmillr/chokidar) in dev to detect when files are created and deleted: #5
- [ ] add unit tests: #6
- [ ] someday: CLI to run server: #7
